#!/bin/bash

echo "Begin setting up Joseph's environment"

# Copy over dotfiles
echo "Copying over dotfiles"
cp .zshrc ${HOME}
cp .vimrc ${HOME}
cp .gitconfig ${HOME}
cp .gitignore_global ${HOME}
cp .tmux.conf ${HOME}

if [ "$(uname)" = 'Linux' ]; then
  # Debian based systems
  if [ "$(grep -Ei 'debian|buntu|mint|kali' /etc/*release)" ]; then
    # Install necessities
    apt-get update
    ## Prevent interactive questions from apt/dpkg
    # `echo |` sends a return to STDIN for prompts
    echo | DEBIAN_FRONTEND=noninteractive apt-get install -y \
      zsh \
      vim \
      git \
      tmux \
      htop \
      irssi \
      curl \
      gettext-base
  fi
fi


# Install prezto for zsh
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Done setting up Joseph's environment"

